#ifndef _AUTO_CONFIG_
#define _AUTO_CONFIG_

#define CONFIG_TRACE 1
#define CONFIG_TRACE_START 0
#define CONFIG_TRACE_END 10000
#define CONFIG_ITRACE 1
#define CONFIG_ITRACE_COND "true"
#define CONFIG_FTRACE 1
#define CONFIG_DIFFTEST 1

#endif